"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _gallery_grid from './gallery-grid.bones.json'

registerBones({
  "gallery-grid": _gallery_grid,
})
